# Generated by Django 2.1.3 on 2019-09-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='finish_date',
            field=models.DateField(default='', null=True, verbose_name='Дата выполнения'),
        ),
    ]
